### ISSUE TITLE
Add button to 2015 symposium to Call for Abstracts page

### ISSUE THREAD

**Issue by chrswng** [GovLab/open-data-symposium-2016#12]
Add white section after submit on easychair section

The <a href="http://www.opendataresearch.org/project/2015/symposium">first Open Data Research Symposium</a> was held as a precursor to the International Open Data Conference in Ottawa on 27th May 2015. Over 60 abstracts were submitted and 31 papers were delivered, of which seven have been accepted for publication in a special issue of the peer reviewed, open access Journal of Community Informatics. 

Button:
<a href="https://docs.google.com/spreadsheets/d/1zvtp2wF9kqrvzXpoUIgq1aYLUcbESJ0WWpShobrXr_A/pubhtml?gid=1456665193&single=true>View 2015 Presenters & Papers</a>

**Comment by juliachrusciel** [comment]
Segment and button added. HTML link to Google doc re: 2015 conference added.
