### ISSUE TITLE
add "#ODRS16" in a few more strategic places

### ISSUE THREAD

**Issue by chrswng** [GovLab/open-data-symposium-2016#21]
- [x] Next to the twitter icon in top nav
- [x] In landing page copy: "The Open Data Research Symposium program committee is pleased to announce that the second Open Data Research Symposium (#ODRS16) will be held on October 5, 2016 prior to the International Open Data Conference 2016 in Madrid, Spain."
- [x] Anywhere else you think would be good

**Comment by juliachrusciel** [comment]
I added the first two with links and the second with hover dark yellow color. I also added a link to #ODRS16 on the questions page with a hover dark yellow.
