### ISSUE TITLE
Edit and add links in the contact us page copy

### ISSUE THREAD

**Issue by chrswng** [GovLab/open-data-symposium-2016#22]
The Open Data Research Symposium is organized by the <a href="http://www.thegovlab.org">GovLab</a> at <a href="http://engineering.nyu.edu/">NYU Tandon School of Engineering</a>, the <a href="http://webfoundation.org/">World Wide Web Foundation</a> and <a href="http://od4d.net/">Open Data for Development</a>. For further information on the Symposium, please email Stefaan Verhulst at [add mailto: link]stefaan@thegovlab.org or use the contact form below.

**Comment by juliachrusciel** [comment]
Links added.
