### ISSUE TITLE
hook up contact us form to andrew@thegovlab.org

### ISSUE THREAD

**Issue by chrswng** [GovLab/open-data-symposium-2016#23]
contact us form submissions will go to andrew at andrew@thegovlab.org 

once you set that, you should send a test email which will send andrew an activation email and I'll ask him to let us know once he's activated it

**Comment by juliachrusciel** [comment]
I set the formspree submission email to andrew@thegovlab.org. I attempted to send a test email and await Andrew's input on what happened on his end.

**Comment by juliachrusciel** [comment]
Changes made. Form works. issue closed.
