### ISSUE TITLE
update programming committee with twitters (and some other minor thangs)

### ISSUE THREAD

**Issue by chrswng** [GovLab/open-data-symposium-2016#36]
Stefaan Verhulst (The GovLab, NYU Tandon School of Engineering) (Co-chair) https://twitter.com/thegovlab

Francois van Schalkwyk (World Wide Web Foundation/Stellenbosch University) (Co-chair)
https://twitter.com/francois_fvs2

Emmy Chirchir (Münster University)
https://twitter.com/ChirchirEmmy

Katie Clancy (IDRC | OD4D)
https://twitter.com/landofkatie

Gisele Craveiro (University of Sao Paulo)

Tim Davies (University of Southampton)
https://twitter.com/timdavies

Kyujin Jung (Tennessee State University)

Fernando Perini (IDRC, Uruguay)
https://twitter.com/fperini

Gustavo Magalhaes (UT Austin | Portugal CoLab)
https://twitter.com/freddygusto

Michelle McLeod (University of the West Indies)
https://twitter.com/DrMTMcLeod

Stefania Milan (University of Amsterdam)
https://twitter.com/annliffey

Andrew Young (The GovLab, NYU Tandon School of Engineering)
https://twitter.com/_AndrewYoung

**Comment by juliachrusciel** [comment]
Twitter icons and links to accounts added.
