### ISSUE TITLE
stefaan's list

### ISSUE THREAD

**Issue by chrswng** [GovLab/open-data-symposium-2016#7]
- [x] Remove YouTube link
- [x] Remove Twitter link or make it link to #odrs16 (or whatever hashtag we are going to use)
- [x] Call for abstracts deadline at the top should be May 23, not September 1
- [x] For the call for Questions - can we have the "What are the questions that open data researchers should be answering?" in the large yellow strip instead of How to Submit a Question?
- [x] Can we add Organization to the Questions form?

**Comment by claudioccm** [comment]
RE: Adding Organization to Form
Julia needs to add that to the form. She created the initial form, so we will need to wait for her, in order for me to not have to re-do it from scratch. We will add it in the coming days.

**Comment by chrswng** [comment]
yeah figured that was the case

@juliachrusciel

**Comment by juliachrusciel** [comment]
I added an organizations category.
